---

- name: Add SSH Key
  authorized_key: 
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"


- name: allow 'pi' to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    line: 'pi ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
            

- name: Disable Password Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backrefs: true

- name: Disable Root Login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backrefs: true
  notify:
    - restart ssh
    

- name: restart ssh
  service:
    name: sshd
    state: restarted

