---

# - name: Add SSH Key
#   authorized_key: 
#     user: "{{ ansible_user }}"
#     state: present
#     key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"


# - name: allow 'pi' to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     line: 'pi ALL=(ALL) NOPASSWD: ALL'
#     validate: 'visudo -cf %s'
            

- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  register: disable_pass


- name: Disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  register: disable_root

- name: Rebooting
  reboot:
  when:
    - disable_pass is changed
    - disable_root is changed
    
