---

- name: Replace pi default password
  hosts: all
  become: yes
  roles:
    - role: password

  vars_prompt:
    - name: "new_pass"
      prompt: "Enter your new password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes