---

- name: Universal tasks
  hosts: k3s
  gather_facts: yes
  become: yes
  roles:
    - role: authentication
#     - role: update
#     - role: network
#     - role: configuration


# - name: Master tasks
#   hosts: master
#   become: yes
#   roles:
#     - role: cluster/master
#   environment:
#     K3S_KUBECONFIG_MODE: 644
#     INSTALL_K3S_EXEC: --no-deploy servicelb --no-deploy traefik


# - name: Worker tasks
  # hosts: worker
  # become: yes
  # roles:
  #   - role: cluster/worker
  # environment:
  #   K3S_KUBECONFIG_MODE: 644
  #   K3S_URL: https://10.0.0.100:6443
  #   K3S_TOKEN: "K1097834b5fd8dbb5f8c14c8f118de85e7ba21031a1491702611528cfd34b5e6057::server:e0c37781e2be45ce17b7b8647fc559fc"
    
