---

- name: Replace pi default password
  hosts: all
  become: yes
  roles:
    - role: password

  vars_prompt:
    - name: "new_pass"
      prompt: "Replace default pass with"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes