---

- name: Master uninstall
  hosts: master
  become: yes
  roles:
    - role: cluster/uninstall_master

- name: Worker uninstall
  hosts: worker
  become: yes
  roles:
    - role: cluster/uninstall_worker
