---

- name: Setting host name
  hostname: name={{inventory_hostname}}
  register: host_name

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
  register: forward_ipv4

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes
  register: forward_ipv6

# - name: install iptables
#   shell: "apt install iptables  && apt install install xtables-addons-common"
#   register: iptables_installed


- name: Flushing iptables
  iptables:
    flush: yes
  register: flush_iptables
  

- name: Set IPv4 legacy tables
  alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables
  register: legacy_ipv4

- name: Set IPv6 legacy tables
  alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables
  register: legacy_ipv6

- name: Rebooting
  reboot:
  when:
    - host_name is changed
    - forward_ipv4 is changed
    - forward_ipv6 is changed
    - iptables_installed is changed
    - flush_iptables is changed
    - legacy_ipv4 is changed
    - legacy_ipv6 is changed


