---

- name: Run installer
  shell: "curl -sfL https://get.k3s.io | sh -s -"
  changed_when: true

- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Enable K3s service
  service:
    name: k3s
    enabled: yes
    state: started

- name: Wait for token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  run_once: true


- name: Get token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  run_once: true

- name: Store token
  set_fact:
    token: "{{ node_token['content'] | b64decode | regex_replace('\n', '')}}"
  run_once: true

- name: Print cluster node token
  debug:
    msg: "{{ node_token }}"

- name: Create ansible_user /.kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy config
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"

- name: Point config to master
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true