---

- name: Export k3s kubeconfig mode
  shell: 'export K3S_KUBECONFIG_MODE="644"'
  changed_when: true

- name: Export k3s master ip
  shell: "export K3S_URL=https://{{ master_ip }}:6443"
  changed_when: true

- name: Export k3s token
  shell: "export K3S_TOKEN={{ hostvars[groups['master'][0]]['token'] }}"
  changed_when: true

- name: Run installer
  shell: "curl -sfL https://get.k3s.io | sh -"
  changed_when: true

- name: Enable reload
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes