---

# - name: Setting variable for K3S_TOKEN
#   shell: echo $K3S_TOKEN
#   environment:
#     K3S_TOKEN: '{{  node_token  }}'


- name: Run installer
  shell: "curl -sfL https://get.k3s.io |  sh -s -"
  changed_when: true

- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Enable k3s service
  service:
    name: k3s-agent
    enabled: yes
    state: started
